version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/cypress-sample-usage
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run
      - store_test_results:  
          path: cypress/reports/junit
      - run: 
          name: "Merge junit xml to json file"
          command: npx mochawesome-merge --reportDir cypress/reports/junit > mochawesome.json
      - run:
          name: "Generate a single HTML Report"
          command: npx mochawesome-report-generator mochawesome.json
      - store_artifacts:
          path: cypress
          
