version: 2.1
orbs:
  node: circleci/node@3.0.0

  jobs:
    test:
      docker:
        - image: node
      steps:
        - checkout
        - run: ls -la
        - run: npm install
        - run: npx cypress run
        - store_test_results:
            path: results/result.xml
        - store_artifacts:
            path: cypress/videos

workflows:
  version: 2
  node-tests:
    jobs:
      - test
